name: queue_app
description: 'CTmax Queues app'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.2
  intl: ^0.20.1
  shared_preferences: ^2.3.4
  network_info_plus: ^6.1.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  audioplayers: ^6.1.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/
    - assets/audio/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/applogo.png' # Только для iOS
  adaptive_icon_background: '#232524' # Укажите цвет фона
  adaptive_icon_foreground: 'assets/applogo.png' # Передний план
  remove_alpha_ios: true
